
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 24 2026 16:35:54 IST (Feb 24 2026 11:05:54 UTC)

// Verification Directory fv/sync_ram 

module sync_ram(clk, rst, we, addr, data_in, data_out);
  input clk, rst, we;
  input [3:0] addr;
  input [7:0] data_in;
  output [7:0] data_out;
  wire clk, rst, we;
  wire [3:0] addr;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire [7:0] \memory[13] ;
  wire [7:0] \memory[10] ;
  wire [7:0] \memory[12] ;
  wire [7:0] \memory[11] ;
  wire [7:0] \memory[15] ;
  wire [7:0] \memory[8] ;
  wire [7:0] \memory[0] ;
  wire [7:0] \memory[3] ;
  wire [7:0] \memory[5] ;
  wire [7:0] \memory[7] ;
  wire [7:0] \memory[1] ;
  wire [7:0] \memory[6] ;
  wire [7:0] \memory[2] ;
  wire [7:0] \memory[4] ;
  wire [7:0] \memory[14] ;
  wire [7:0] \memory[9] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_13, n_14, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_242, n_243, n_244, n_245, n_246, n_247;
  wire n_248, n_249, n_250, n_251, n_252, n_253, n_254, n_255;
  wire n_256, n_257, n_258, n_259, n_260, n_261, n_262, n_263;
  wire n_264, n_265, n_266, n_267, n_268, n_269, n_270, n_271;
  wire n_272, n_273, n_274, n_275, n_276, n_277, n_278, n_279;
  wire n_280, n_281, n_283, n_284, n_285, n_286, n_287, n_288;
  wire n_289, n_290, n_291, n_292, n_293, n_294, n_295, n_296;
  wire n_297, n_298, n_299, n_300, n_301, n_302, n_303, n_304;
  wire n_305, n_306, n_307, n_308, n_309, n_310, n_326, n_327;
  wire n_328, n_329;
  DFFQX4 \data_out_reg[0] (.CK (clk), .D (n_308), .Q (data_out[0]));
  DFFQX4 \data_out_reg[1] (.CK (clk), .D (n_303), .Q (data_out[1]));
  DFFQX4 \data_out_reg[4] (.CK (clk), .D (n_309), .Q (data_out[4]));
  DFFQX4 \data_out_reg[5] (.CK (clk), .D (n_304), .Q (data_out[5]));
  DFFQX4 \data_out_reg[2] (.CK (clk), .D (n_305), .Q (data_out[2]));
  DFFQX4 \data_out_reg[6] (.CK (clk), .D (n_307), .Q (data_out[6]));
  DFFQX4 \data_out_reg[3] (.CK (clk), .D (n_306), .Q (data_out[3]));
  DFFQX4 \data_out_reg[7] (.CK (clk), .D (n_310), .Q (data_out[7]));
  NAND4XL g7921__2398(.A (n_79), .B (n_259), .C (n_296), .D (n_286), .Y
       (n_310));
  NAND4XL g7916__5107(.A (n_68), .B (n_277), .C (n_302), .D (n_288), .Y
       (n_309));
  NAND4XL g7920__6260(.A (n_73), .B (n_274), .C (n_295), .D (n_291), .Y
       (n_308));
  NAND4XL g7917__4319(.A (n_53), .B (n_267), .C (n_297), .D (n_287), .Y
       (n_307));
  NAND4XL g7918__8428(.A (n_77), .B (n_265), .C (n_294), .D (n_285), .Y
       (n_306));
  NAND4XL g7915__5526(.A (n_92), .B (n_269), .C (n_298), .D (n_293), .Y
       (n_305));
  NAND4XL g7914__6783(.A (n_57), .B (n_271), .C (n_301), .D (n_289), .Y
       (n_304));
  NAND4XL g7919__3680(.A (n_76), .B (n_264), .C (n_292), .D (n_290), .Y
       (n_303));
  DFFQXL \memory_reg[13][2] (.CK (clk), .D (n_266), .Q (\memory[13]
       [2]));
  DFFQX1 \memory_reg[10][7] (.CK (clk), .D (n_275), .Q (\memory[10]
       [7]));
  DFFQXL \memory_reg[13][0] (.CK (clk), .D (n_263), .Q (\memory[13]
       [0]));
  DFFQXL \memory_reg[13][1] (.CK (clk), .D (n_260), .Q (\memory[13]
       [1]));
  DFFQX1 \memory_reg[10][5] (.CK (clk), .D (n_278), .Q (\memory[10]
       [5]));
  DFFQXL \memory_reg[13][3] (.CK (clk), .D (n_258), .Q (\memory[13]
       [3]));
  DFFQXL \memory_reg[13][4] (.CK (clk), .D (n_257), .Q (\memory[13]
       [4]));
  DFFQXL \memory_reg[13][5] (.CK (clk), .D (n_256), .Q (\memory[13]
       [5]));
  DFFQX1 \memory_reg[10][2] (.CK (clk), .D (n_261), .Q (\memory[10]
       [2]));
  DFFQXL \memory_reg[13][7] (.CK (clk), .D (n_254), .Q (\memory[13]
       [7]));
  DFFQX1 \memory_reg[10][0] (.CK (clk), .D (n_283), .Q (\memory[10]
       [0]));
  DFFQX1 \memory_reg[10][1] (.CK (clk), .D (n_280), .Q (\memory[10]
       [1]));
  DFFQXL \memory_reg[13][6] (.CK (clk), .D (n_255), .Q (\memory[13]
       [6]));
  DFFQX1 \memory_reg[10][3] (.CK (clk), .D (n_284), .Q (\memory[10]
       [3]));
  DFFQX1 \memory_reg[10][4] (.CK (clk), .D (n_279), .Q (\memory[10]
       [4]));
  DFFQX1 \memory_reg[10][6] (.CK (clk), .D (n_276), .Q (\memory[10]
       [6]));
  AOI221XL g8129__1617(.A0 (\memory[12] [4]), .A1 (n_300), .B0
       (\memory[11] [4]), .B1 (n_299), .C0 (n_113), .Y (n_302));
  AOI221XL g8059__2802(.A0 (\memory[12] [5]), .A1 (n_300), .B0
       (\memory[11] [5]), .B1 (n_299), .C0 (n_89), .Y (n_301));
  AOI221XL g8060__1705(.A0 (\memory[12] [2]), .A1 (n_300), .B0
       (\memory[11] [2]), .B1 (n_299), .C0 (n_85), .Y (n_298));
  AOI221XL g8061__5122(.A0 (\memory[12] [6]), .A1 (n_300), .B0
       (\memory[11] [6]), .B1 (n_299), .C0 (n_84), .Y (n_297));
  AOI221XL g8062__8246(.A0 (\memory[12] [7]), .A1 (n_300), .B0
       (\memory[11] [7]), .B1 (n_299), .C0 (n_104), .Y (n_296));
  AOI221XL g8063__7098(.A0 (\memory[12] [0]), .A1 (n_300), .B0
       (\memory[11] [0]), .B1 (n_299), .C0 (n_86), .Y (n_295));
  DFFQX1 \memory_reg[15][1] (.CK (clk), .D (n_178), .Q (\memory[15]
       [1]));
  DFFQX1 \memory_reg[8][1] (.CK (clk), .D (n_115), .Q (\memory[8] [1]));
  DFFQX1 \memory_reg[0][2] (.CK (clk), .D (n_203), .Q (\memory[0] [2]));
  DFFQX1 \memory_reg[3][3] (.CK (clk), .D (n_166), .Q (\memory[3] [3]));
  DFFQX1 \memory_reg[5][5] (.CK (clk), .D (n_139), .Q (\memory[5] [5]));
  DFFQX1 \memory_reg[7][1] (.CK (clk), .D (n_125), .Q (\memory[7] [1]));
  DFFQX1 \memory_reg[1][4] (.CK (clk), .D (n_216), .Q (\memory[1] [4]));
  DFFQX1 \memory_reg[1][5] (.CK (clk), .D (n_214), .Q (\memory[1] [5]));
  DFFQX1 \memory_reg[1][6] (.CK (clk), .D (n_211), .Q (\memory[1] [6]));
  DFFQX1 \memory_reg[6][5] (.CK (clk), .D (n_129), .Q (\memory[6] [5]));
  DFFQX1 \memory_reg[1][7] (.CK (clk), .D (n_207), .Q (\memory[1] [7]));
  DFFQX1 \memory_reg[2][0] (.CK (clk), .D (n_206), .Q (\memory[2] [0]));
  DFFQX1 \memory_reg[2][1] (.CK (clk), .D (n_202), .Q (\memory[2] [1]));
  DFFQX1 \memory_reg[6][1] (.CK (clk), .D (n_135), .Q (\memory[6] [1]));
  DFFQX1 \memory_reg[2][2] (.CK (clk), .D (n_200), .Q (\memory[2] [2]));
  DFFQX1 \memory_reg[2][3] (.CK (clk), .D (n_194), .Q (\memory[2] [3]));
  DFFQX1 \memory_reg[2][4] (.CK (clk), .D (n_191), .Q (\memory[2] [4]));
  DFFQX1 \memory_reg[1][3] (.CK (clk), .D (n_182), .Q (\memory[1] [3]));
  DFFQX1 \memory_reg[2][5] (.CK (clk), .D (n_188), .Q (\memory[2] [5]));
  DFFQX1 \memory_reg[2][6] (.CK (clk), .D (n_186), .Q (\memory[2] [6]));
  DFFQX1 \memory_reg[2][7] (.CK (clk), .D (n_253), .Q (\memory[2] [7]));
  DFFQX1 \memory_reg[5][1] (.CK (clk), .D (n_145), .Q (\memory[5] [1]));
  DFFQX1 \memory_reg[3][0] (.CK (clk), .D (n_179), .Q (\memory[3] [0]));
  DFFQX1 \memory_reg[3][1] (.CK (clk), .D (n_174), .Q (\memory[3] [1]));
  DFFQX1 \memory_reg[4][5] (.CK (clk), .D (n_149), .Q (\memory[4] [5]));
  DFFQX1 \memory_reg[3][2] (.CK (clk), .D (n_170), .Q (\memory[3] [2]));
  DFFQX1 \memory_reg[11][5] (.CK (clk), .D (n_229), .Q (\memory[11]
       [5]));
  DFFQX1 \memory_reg[3][4] (.CK (clk), .D (n_163), .Q (\memory[3] [4]));
  DFFQX1 \memory_reg[3][5] (.CK (clk), .D (n_159), .Q (\memory[3] [5]));
  DFFQX1 \memory_reg[3][6] (.CK (clk), .D (n_158), .Q (\memory[3] [6]));
  DFFQX1 \memory_reg[3][7] (.CK (clk), .D (n_157), .Q (\memory[3] [7]));
  DFFQX1 \memory_reg[4][0] (.CK (clk), .D (n_156), .Q (\memory[4] [0]));
  DFFQX1 \memory_reg[4][1] (.CK (clk), .D (n_155), .Q (\memory[4] [1]));
  DFFQX1 \memory_reg[4][2] (.CK (clk), .D (n_152), .Q (\memory[4] [2]));
  DFFQX1 \memory_reg[4][3] (.CK (clk), .D (n_151), .Q (\memory[4] [3]));
  DFFQX1 \memory_reg[4][4] (.CK (clk), .D (n_150), .Q (\memory[4] [4]));
  DFFQX1 \memory_reg[4][6] (.CK (clk), .D (n_148), .Q (\memory[4] [6]));
  DFFQX1 \memory_reg[4][7] (.CK (clk), .D (n_147), .Q (\memory[4] [7]));
  DFFQX1 \memory_reg[5][0] (.CK (clk), .D (n_146), .Q (\memory[5] [0]));
  DFFQX1 \memory_reg[12][6] (.CK (clk), .D (n_218), .Q (\memory[12]
       [6]));
  DFFQX1 \memory_reg[5][2] (.CK (clk), .D (n_142), .Q (\memory[5] [2]));
  DFFQX1 \memory_reg[5][3] (.CK (clk), .D (n_141), .Q (\memory[5] [3]));
  DFFQX1 \memory_reg[5][4] (.CK (clk), .D (n_140), .Q (\memory[5] [4]));
  DFFQX1 \memory_reg[5][6] (.CK (clk), .D (n_138), .Q (\memory[5] [6]));
  DFFQX1 \memory_reg[5][7] (.CK (clk), .D (n_137), .Q (\memory[5] [7]));
  DFFQX1 \memory_reg[6][0] (.CK (clk), .D (n_136), .Q (\memory[6] [0]));
  DFFQX1 \memory_reg[6][2] (.CK (clk), .D (n_132), .Q (\memory[6] [2]));
  DFFQX1 \memory_reg[6][3] (.CK (clk), .D (n_131), .Q (\memory[6] [3]));
  DFFQX1 \memory_reg[6][4] (.CK (clk), .D (n_130), .Q (\memory[6] [4]));
  DFFQX1 \memory_reg[6][6] (.CK (clk), .D (n_128), .Q (\memory[6] [6]));
  DFFQX1 \memory_reg[6][7] (.CK (clk), .D (n_127), .Q (\memory[6] [7]));
  DFFQX1 \memory_reg[7][0] (.CK (clk), .D (n_126), .Q (\memory[7] [0]));
  DFFQX1 \memory_reg[7][2] (.CK (clk), .D (n_122), .Q (\memory[7] [2]));
  DFFQX1 \memory_reg[7][3] (.CK (clk), .D (n_121), .Q (\memory[7] [3]));
  DFFQX1 \memory_reg[7][4] (.CK (clk), .D (n_120), .Q (\memory[7] [4]));
  DFFQX1 \memory_reg[7][5] (.CK (clk), .D (n_119), .Q (\memory[7] [5]));
  DFFQX1 \memory_reg[7][6] (.CK (clk), .D (n_118), .Q (\memory[7] [6]));
  DFFQX1 \memory_reg[7][7] (.CK (clk), .D (n_117), .Q (\memory[7] [7]));
  AOI221XL g8064__6131(.A0 (\memory[12] [3]), .A1 (n_300), .B0
       (\memory[14] [3]), .B1 (n_91), .C0 (n_72), .Y (n_294));
  AND4XL g7990__1881(.A (n_87), .B (n_49), .C (n_83), .D (n_51), .Y
       (n_293));
  AOI221XL g8065__5115(.A0 (\memory[12] [1]), .A1 (n_300), .B0
       (\memory[11] [1]), .B1 (n_299), .C0 (n_74), .Y (n_292));
  AND4XL g7991__7482(.A (n_81), .B (n_52), .C (n_90), .D (n_58), .Y
       (n_291));
  AND4XL g7992__4733(.A (n_96), .B (n_64), .C (n_100), .D (n_67), .Y
       (n_290));
  AND4XL g7993__6161(.A (n_78), .B (n_55), .C (n_101), .D (n_56), .Y
       (n_289));
  AND4XL g7994__9315(.A (n_94), .B (n_60), .C (n_97), .D (n_62), .Y
       (n_288));
  AND4XL g7995__9945(.A (n_80), .B (n_48), .C (n_47), .D (n_82), .Y
       (n_287));
  AND4XL g7996__2883(.A (n_71), .B (n_46), .C (n_75), .D (n_54), .Y
       (n_286));
  AND4XL g7997__2346(.A (n_69), .B (n_70), .C (n_50), .D (n_66), .Y
       (n_285));
  DFFQX1 \memory_reg[9][2] (.CK (clk), .D (n_242), .Q (\memory[9] [2]));
  DFFQX1 \memory_reg[9][6] (.CK (clk), .D (n_238), .Q (\memory[9] [6]));
  DFFQX1 \memory_reg[11][0] (.CK (clk), .D (n_236), .Q (\memory[11]
       [0]));
  DFFQX1 \memory_reg[11][2] (.CK (clk), .D (n_232), .Q (\memory[11]
       [2]));
  DFFQX1 \memory_reg[11][3] (.CK (clk), .D (n_231), .Q (\memory[11]
       [3]));
  DFFQX1 \memory_reg[11][4] (.CK (clk), .D (n_230), .Q (\memory[11]
       [4]));
  DFFQX1 \memory_reg[11][6] (.CK (clk), .D (n_228), .Q (\memory[11]
       [6]));
  DFFQX1 \memory_reg[11][7] (.CK (clk), .D (n_227), .Q (\memory[11]
       [7]));
  DFFQX1 \memory_reg[12][0] (.CK (clk), .D (n_226), .Q (\memory[12]
       [0]));
  DFFQX1 \memory_reg[12][2] (.CK (clk), .D (n_222), .Q (\memory[12]
       [2]));
  DFFQX1 \memory_reg[12][3] (.CK (clk), .D (n_221), .Q (\memory[12]
       [3]));
  DFFQX1 \memory_reg[12][4] (.CK (clk), .D (n_220), .Q (\memory[12]
       [4]));
  DFFQX1 \memory_reg[12][5] (.CK (clk), .D (n_219), .Q (\memory[12]
       [5]));
  DFFQX1 \memory_reg[8][2] (.CK (clk), .D (n_181), .Q (\memory[8] [2]));
  DFFQX1 \memory_reg[12][7] (.CK (clk), .D (n_217), .Q (\memory[12]
       [7]));
  DFFQX1 \memory_reg[0][0] (.CK (clk), .D (n_215), .Q (\memory[0] [0]));
  DFFQX1 \memory_reg[8][3] (.CK (clk), .D (n_248), .Q (\memory[8] [3]));
  DFFQX1 \memory_reg[0][1] (.CK (clk), .D (n_210), .Q (\memory[0] [1]));
  DFFQX1 \memory_reg[9][7] (.CK (clk), .D (n_237), .Q (\memory[9] [7]));
  DFFQX1 \memory_reg[14][0] (.CK (clk), .D (n_199), .Q (\memory[14]
       [0]));
  DFFQX1 \memory_reg[0][3] (.CK (clk), .D (n_201), .Q (\memory[0] [3]));
  DFFQX1 \memory_reg[14][2] (.CK (clk), .D (n_195), .Q (\memory[14]
       [2]));
  DFFQX1 \memory_reg[8][0] (.CK (clk), .D (n_116), .Q (\memory[8] [0]));
  DFFQX1 \memory_reg[0][5] (.CK (clk), .D (n_192), .Q (\memory[0] [5]));
  DFFQX1 \memory_reg[14][4] (.CK (clk), .D (n_189), .Q (\memory[14]
       [4]));
  DFFQX1 \memory_reg[14][5] (.CK (clk), .D (n_187), .Q (\memory[14]
       [5]));
  DFFQX1 \memory_reg[14][6] (.CK (clk), .D (n_185), .Q (\memory[14]
       [6]));
  DFFQX1 \memory_reg[14][7] (.CK (clk), .D (n_183), .Q (\memory[14]
       [7]));
  DFFQX1 \memory_reg[0][7] (.CK (clk), .D (n_114), .Q (\memory[0] [7]));
  DFFQX1 \memory_reg[15][0] (.CK (clk), .D (n_180), .Q (\memory[15]
       [0]));
  DFFQX1 \memory_reg[15][2] (.CK (clk), .D (n_171), .Q (\memory[15]
       [2]));
  DFFQX1 \memory_reg[15][3] (.CK (clk), .D (n_169), .Q (\memory[15]
       [3]));
  DFFQX1 \memory_reg[15][4] (.CK (clk), .D (n_168), .Q (\memory[15]
       [4]));
  DFFQX1 \memory_reg[15][5] (.CK (clk), .D (n_165), .Q (\memory[15]
       [5]));
  DFFQX1 \memory_reg[1][1] (.CK (clk), .D (n_167), .Q (\memory[1] [1]));
  DFFQX1 \memory_reg[15][6] (.CK (clk), .D (n_164), .Q (\memory[15]
       [6]));
  DFFQX1 \memory_reg[1][0] (.CK (clk), .D (n_175), .Q (\memory[1] [0]));
  DFFQX1 \memory_reg[1][2] (.CK (clk), .D (n_162), .Q (\memory[1] [2]));
  DFFQX1 \memory_reg[8][4] (.CK (clk), .D (n_160), .Q (\memory[8] [4]));
  DFFQX1 \memory_reg[8][6] (.CK (clk), .D (n_251), .Q (\memory[8] [6]));
  DFFQX1 \memory_reg[8][7] (.CK (clk), .D (n_247), .Q (\memory[8] [7]));
  DFFQX1 \memory_reg[9][0] (.CK (clk), .D (n_246), .Q (\memory[9] [0]));
  DFFQX1 \memory_reg[12][1] (.CK (clk), .D (n_225), .Q (\memory[12]
       [1]));
  DFFQX1 \memory_reg[15][7] (.CK (clk), .D (n_161), .Q (\memory[15]
       [7]));
  DFFQX1 \memory_reg[0][4] (.CK (clk), .D (n_193), .Q (\memory[0] [4]));
  DFFQX1 \memory_reg[9][3] (.CK (clk), .D (n_241), .Q (\memory[9] [3]));
  DFFQX1 \memory_reg[9][4] (.CK (clk), .D (n_240), .Q (\memory[9] [4]));
  DFFQX1 \memory_reg[14][3] (.CK (clk), .D (n_190), .Q (\memory[14]
       [3]));
  DFFQX1 \memory_reg[11][1] (.CK (clk), .D (n_235), .Q (\memory[11]
       [1]));
  DFFQX1 \memory_reg[8][5] (.CK (clk), .D (n_252), .Q (\memory[8] [5]));
  DFFQX1 \memory_reg[0][6] (.CK (clk), .D (n_184), .Q (\memory[0] [6]));
  DFFQX1 \memory_reg[9][5] (.CK (clk), .D (n_239), .Q (\memory[9] [5]));
  DFFQX1 \memory_reg[14][1] (.CK (clk), .D (n_198), .Q (\memory[14]
       [1]));
  DFFQX1 \memory_reg[9][1] (.CK (clk), .D (n_245), .Q (\memory[9] [1]));
  AO22X1 g8145__1666(.A0 (\memory[10] [3]), .A1 (n_326), .B0
       (data_in[3]), .B1 (n_281), .Y (n_284));
  AO22X1 g8142__7410(.A0 (\memory[10] [0]), .A1 (n_326), .B0
       (data_in[0]), .B1 (n_281), .Y (n_283));
  AO22X1 g8143__6417(.A0 (\memory[10] [1]), .A1 (n_326), .B0
       (data_in[1]), .B1 (n_281), .Y (n_280));
  AO22X1 g8146__5477(.A0 (\memory[10] [4]), .A1 (n_326), .B0
       (data_in[4]), .B1 (n_281), .Y (n_279));
  AO22X1 g8147__2398(.A0 (\memory[10] [5]), .A1 (n_326), .B0
       (data_in[5]), .B1 (n_281), .Y (n_278));
  AOI222XL g8066__5107(.A0 (\memory[13] [4]), .A1 (n_270), .B0
       (\memory[15] [4]), .B1 (n_273), .C0 (n_272), .C1 (data_out[4]),
       .Y (n_277));
  AO22X1 g8148__6260(.A0 (\memory[10] [6]), .A1 (n_326), .B0
       (data_in[6]), .B1 (n_281), .Y (n_276));
  AO22X1 g8149__4319(.A0 (\memory[10] [7]), .A1 (n_326), .B0
       (data_in[7]), .B1 (n_281), .Y (n_275));
  AOI222XL g8067__8428(.A0 (n_268), .A1 (\memory[0] [0]), .B0
       (\memory[15] [0]), .B1 (n_273), .C0 (data_out[0]), .C1 (n_272),
       .Y (n_274));
  AOI222XL g8068__5526(.A0 (\memory[13] [5]), .A1 (n_270), .B0
       (\memory[15] [5]), .B1 (n_273), .C0 (n_272), .C1 (data_out[5]),
       .Y (n_271));
  AOI222XL g8069__6783(.A0 (n_268), .A1 (\memory[0] [2]), .B0
       (\memory[15] [2]), .B1 (n_273), .C0 (data_out[2]), .C1 (n_272),
       .Y (n_269));
  AOI222XL g8070__3680(.A0 (\memory[13] [6]), .A1 (n_270), .B0
       (\memory[15] [6]), .B1 (n_273), .C0 (n_272), .C1 (data_out[6]),
       .Y (n_267));
  OAI21XL g8169__1617(.A0 (n_262), .A1 (n_1), .B0 (n_109), .Y (n_266));
  AOI222XL g8072__2802(.A0 (\memory[15] [3]), .A1 (n_273), .B0
       (\memory[2] [3]), .B1 (n_95), .C0 (n_272), .C1 (data_out[3]), .Y
       (n_265));
  AOI222XL g8073__1705(.A0 (n_268), .A1 (\memory[0] [1]), .B0
       (\memory[15] [1]), .B1 (n_273), .C0 (data_out[1]), .C1 (n_272),
       .Y (n_264));
  OAI21XL g8167__5122(.A0 (n_262), .A1 (n_4), .B0 (n_112), .Y (n_263));
  AO22X1 g8144__8246(.A0 (\memory[10] [2]), .A1 (n_326), .B0
       (data_in[2]), .B1 (n_281), .Y (n_261));
  OAI21XL g8168__7098(.A0 (n_262), .A1 (n_7), .B0 (n_111), .Y (n_260));
  AOI222XL g8071__6131(.A0 (n_268), .A1 (\memory[0] [7]), .B0
       (\memory[15] [7]), .B1 (n_273), .C0 (data_out[7]), .C1 (n_272),
       .Y (n_259));
  OAI21XL g8170__1881(.A0 (n_262), .A1 (n_6), .B0 (n_108), .Y (n_258));
  OAI21XL g8172__5115(.A0 (n_262), .A1 (n_3), .B0 (n_107), .Y (n_257));
  OAI21XL g8173__7482(.A0 (n_262), .A1 (n_0), .B0 (n_106), .Y (n_256));
  OAI21XL g8174__4733(.A0 (n_262), .A1 (n_5), .B0 (n_88), .Y (n_255));
  OAI21XL g8176__6161(.A0 (n_262), .A1 (n_2), .B0 (n_105), .Y (n_254));
  AO22XL g8085__9315(.A0 (\memory[2] [7]), .A1 (n_205), .B0
       (data_in[7]), .B1 (n_204), .Y (n_253));
  AO22XL g8131__9945(.A0 (\memory[8] [5]), .A1 (n_250), .B0
       (data_in[5]), .B1 (n_249), .Y (n_252));
  AO22XL g8132__2883(.A0 (\memory[8] [6]), .A1 (n_250), .B0
       (data_in[6]), .B1 (n_249), .Y (n_251));
  AO22XL g8058__2346(.A0 (\memory[8] [3]), .A1 (n_250), .B0
       (data_in[3]), .B1 (n_249), .Y (n_248));
  AO22XL g8133__1666(.A0 (\memory[8] [7]), .A1 (n_250), .B0
       (data_in[7]), .B1 (n_249), .Y (n_247));
  AO22XL g8134__7410(.A0 (\memory[9] [0]), .A1 (n_244), .B0
       (data_in[0]), .B1 (n_243), .Y (n_246));
  AO22XL g8135__6417(.A0 (\memory[9] [1]), .A1 (n_244), .B0
       (data_in[1]), .B1 (n_243), .Y (n_245));
  AO22XL g8136__5477(.A0 (\memory[9] [2]), .A1 (n_244), .B0
       (data_in[2]), .B1 (n_243), .Y (n_242));
  AO22XL g8137__2398(.A0 (\memory[9] [3]), .A1 (n_244), .B0
       (data_in[3]), .B1 (n_243), .Y (n_241));
  AO22XL g8138__5107(.A0 (\memory[9] [4]), .A1 (n_244), .B0
       (data_in[4]), .B1 (n_243), .Y (n_240));
  AO22XL g8139__6260(.A0 (\memory[9] [5]), .A1 (n_244), .B0
       (data_in[5]), .B1 (n_243), .Y (n_239));
  AO22XL g8140__4319(.A0 (\memory[9] [6]), .A1 (n_244), .B0
       (data_in[6]), .B1 (n_243), .Y (n_238));
  AO22XL g8141__8428(.A0 (\memory[9] [7]), .A1 (n_244), .B0
       (data_in[7]), .B1 (n_243), .Y (n_237));
  AO22X1 g8150__5526(.A0 (\memory[11] [0]), .A1 (n_234), .B0
       (data_in[0]), .B1 (n_233), .Y (n_236));
  AO22X1 g8151__6783(.A0 (\memory[11] [1]), .A1 (n_234), .B0
       (data_in[1]), .B1 (n_233), .Y (n_235));
  AO22X1 g8152__3680(.A0 (\memory[11] [2]), .A1 (n_234), .B0
       (data_in[2]), .B1 (n_233), .Y (n_232));
  AO22X1 g8153__1617(.A0 (\memory[11] [3]), .A1 (n_234), .B0
       (data_in[3]), .B1 (n_233), .Y (n_231));
  AO22X1 g8154__2802(.A0 (\memory[11] [4]), .A1 (n_234), .B0
       (data_in[4]), .B1 (n_233), .Y (n_230));
  AO22X1 g8155__1705(.A0 (\memory[11] [5]), .A1 (n_234), .B0
       (data_in[5]), .B1 (n_233), .Y (n_229));
  AO22X1 g8156__5122(.A0 (\memory[11] [6]), .A1 (n_234), .B0
       (data_in[6]), .B1 (n_233), .Y (n_228));
  AO22X1 g8157__8246(.A0 (\memory[11] [7]), .A1 (n_234), .B0
       (data_in[7]), .B1 (n_233), .Y (n_227));
  AO22X1 g8158__7098(.A0 (\memory[12] [0]), .A1 (n_224), .B0
       (data_in[0]), .B1 (n_223), .Y (n_226));
  AO22X1 g8159__6131(.A0 (\memory[12] [1]), .A1 (n_224), .B0
       (data_in[1]), .B1 (n_223), .Y (n_225));
  AO22X1 g8160__1881(.A0 (\memory[12] [2]), .A1 (n_224), .B0
       (data_in[2]), .B1 (n_223), .Y (n_222));
  AO22X1 g8161__5115(.A0 (\memory[12] [3]), .A1 (n_224), .B0
       (data_in[3]), .B1 (n_223), .Y (n_221));
  AO22X1 g8162__7482(.A0 (\memory[12] [4]), .A1 (n_224), .B0
       (data_in[4]), .B1 (n_223), .Y (n_220));
  AO22X1 g8163__4733(.A0 (\memory[12] [5]), .A1 (n_224), .B0
       (data_in[5]), .B1 (n_223), .Y (n_219));
  AO22X1 g8164__6161(.A0 (\memory[12] [6]), .A1 (n_224), .B0
       (data_in[6]), .B1 (n_223), .Y (n_218));
  AO22X1 g8165__9315(.A0 (\memory[12] [7]), .A1 (n_224), .B0
       (data_in[7]), .B1 (n_223), .Y (n_217));
  AO22XL g8074__9945(.A0 (\memory[1] [4]), .A1 (n_213), .B0
       (data_in[4]), .B1 (n_212), .Y (n_216));
  AO22XL g8166__2883(.A0 (\memory[0] [0]), .A1 (n_209), .B0
       (data_in[0]), .B1 (n_208), .Y (n_215));
  AO22XL g8075__2346(.A0 (\memory[1] [5]), .A1 (n_213), .B0
       (data_in[5]), .B1 (n_212), .Y (n_214));
  AO22XL g8076__1666(.A0 (\memory[1] [6]), .A1 (n_213), .B0
       (data_in[6]), .B1 (n_212), .Y (n_211));
  AO22XL g8171__7410(.A0 (\memory[0] [1]), .A1 (n_209), .B0
       (data_in[1]), .B1 (n_208), .Y (n_210));
  AO22XL g8077__6417(.A0 (\memory[1] [7]), .A1 (n_213), .B0
       (data_in[7]), .B1 (n_212), .Y (n_207));
  AO22XL g8078__5477(.A0 (\memory[2] [0]), .A1 (n_205), .B0
       (data_in[0]), .B1 (n_204), .Y (n_206));
  AO22XL g8175__2398(.A0 (\memory[0] [2]), .A1 (n_209), .B0
       (data_in[2]), .B1 (n_208), .Y (n_203));
  AO22XL g8079__5107(.A0 (\memory[2] [1]), .A1 (n_205), .B0
       (data_in[1]), .B1 (n_204), .Y (n_202));
  AO22XL g8177__6260(.A0 (\memory[0] [3]), .A1 (n_209), .B0
       (data_in[3]), .B1 (n_208), .Y (n_201));
  AO22XL g8080__4319(.A0 (\memory[2] [2]), .A1 (n_205), .B0
       (data_in[2]), .B1 (n_204), .Y (n_200));
  AO22X1 g8178__8428(.A0 (\memory[14] [0]), .A1 (n_197), .B0
       (data_in[0]), .B1 (n_196), .Y (n_199));
  AO22X1 g8179__5526(.A0 (\memory[14] [1]), .A1 (n_197), .B0
       (data_in[1]), .B1 (n_196), .Y (n_198));
  AO22X1 g8180__6783(.A0 (\memory[14] [2]), .A1 (n_197), .B0
       (data_in[2]), .B1 (n_196), .Y (n_195));
  AO22XL g8081__3680(.A0 (\memory[2] [3]), .A1 (n_205), .B0
       (data_in[3]), .B1 (n_204), .Y (n_194));
  AO22XL g8181__1617(.A0 (\memory[0] [4]), .A1 (n_209), .B0
       (data_in[4]), .B1 (n_208), .Y (n_193));
  AO22XL g8182__2802(.A0 (\memory[0] [5]), .A1 (n_209), .B0
       (data_in[5]), .B1 (n_208), .Y (n_192));
  AO22XL g8082__1705(.A0 (\memory[2] [4]), .A1 (n_205), .B0
       (data_in[4]), .B1 (n_204), .Y (n_191));
  AO22X1 g8183__5122(.A0 (\memory[14] [3]), .A1 (n_197), .B0
       (data_in[3]), .B1 (n_196), .Y (n_190));
  AO22X1 g8184__8246(.A0 (\memory[14] [4]), .A1 (n_197), .B0
       (data_in[4]), .B1 (n_196), .Y (n_189));
  AO22XL g8083__7098(.A0 (\memory[2] [5]), .A1 (n_205), .B0
       (data_in[5]), .B1 (n_204), .Y (n_188));
  AO22X1 g8185__6131(.A0 (\memory[14] [5]), .A1 (n_197), .B0
       (data_in[5]), .B1 (n_196), .Y (n_187));
  AO22XL g8084__1881(.A0 (\memory[2] [6]), .A1 (n_205), .B0
       (data_in[6]), .B1 (n_204), .Y (n_186));
  AO22X1 g8186__5115(.A0 (\memory[14] [6]), .A1 (n_197), .B0
       (data_in[6]), .B1 (n_196), .Y (n_185));
  AO22XL g8187__7482(.A0 (\memory[0] [6]), .A1 (n_209), .B0
       (data_in[6]), .B1 (n_208), .Y (n_184));
  AO22X1 g8188__4733(.A0 (\memory[14] [7]), .A1 (n_197), .B0
       (data_in[7]), .B1 (n_196), .Y (n_183));
  AO22XL g8130__6161(.A0 (\memory[1] [3]), .A1 (n_213), .B0
       (data_in[3]), .B1 (n_212), .Y (n_182));
  AO22XL g8128__9315(.A0 (\memory[8] [2]), .A1 (n_250), .B0
       (data_in[2]), .B1 (n_249), .Y (n_181));
  AO22X1 g8190__9945(.A0 (\memory[15] [0]), .A1 (n_177), .B0
       (data_in[0]), .B1 (n_176), .Y (n_180));
  AO22X1 g8086__2883(.A0 (\memory[3] [0]), .A1 (n_173), .B0
       (data_in[0]), .B1 (n_172), .Y (n_179));
  AO22X1 g8191__2346(.A0 (\memory[15] [1]), .A1 (n_177), .B0
       (data_in[1]), .B1 (n_176), .Y (n_178));
  AO22XL g8192__1666(.A0 (\memory[1] [0]), .A1 (n_213), .B0
       (data_in[0]), .B1 (n_212), .Y (n_175));
  AO22X1 g8087__7410(.A0 (\memory[3] [1]), .A1 (n_173), .B0
       (data_in[1]), .B1 (n_172), .Y (n_174));
  AO22X1 g8193__6417(.A0 (\memory[15] [2]), .A1 (n_177), .B0
       (data_in[2]), .B1 (n_176), .Y (n_171));
  AO22X1 g8088__5477(.A0 (\memory[3] [2]), .A1 (n_173), .B0
       (data_in[2]), .B1 (n_172), .Y (n_170));
  AO22X1 g8194__2398(.A0 (\memory[15] [3]), .A1 (n_177), .B0
       (data_in[3]), .B1 (n_176), .Y (n_169));
  AO22X1 g8195__5107(.A0 (\memory[15] [4]), .A1 (n_177), .B0
       (data_in[4]), .B1 (n_176), .Y (n_168));
  AO22XL g8196__6260(.A0 (\memory[1] [1]), .A1 (n_213), .B0
       (data_in[1]), .B1 (n_212), .Y (n_167));
  AO22X1 g8089__4319(.A0 (\memory[3] [3]), .A1 (n_173), .B0
       (data_in[3]), .B1 (n_172), .Y (n_166));
  AO22X1 g8197__8428(.A0 (\memory[15] [5]), .A1 (n_177), .B0
       (data_in[5]), .B1 (n_176), .Y (n_165));
  AO22X1 g8198__5526(.A0 (\memory[15] [6]), .A1 (n_177), .B0
       (data_in[6]), .B1 (n_176), .Y (n_164));
  AO22X1 g8090__6783(.A0 (\memory[3] [4]), .A1 (n_173), .B0
       (data_in[4]), .B1 (n_172), .Y (n_163));
  AO22XL g8199__3680(.A0 (\memory[1] [2]), .A1 (n_213), .B0
       (data_in[2]), .B1 (n_212), .Y (n_162));
  AO22X1 g8200__1617(.A0 (\memory[15] [7]), .A1 (n_177), .B0
       (data_in[7]), .B1 (n_176), .Y (n_161));
  AO22XL g8201__2802(.A0 (\memory[8] [4]), .A1 (n_250), .B0
       (data_in[4]), .B1 (n_249), .Y (n_160));
  AO22X1 g8091__1705(.A0 (\memory[3] [5]), .A1 (n_173), .B0
       (data_in[5]), .B1 (n_172), .Y (n_159));
  AO22X1 g8092__5122(.A0 (\memory[3] [6]), .A1 (n_173), .B0
       (data_in[6]), .B1 (n_172), .Y (n_158));
  AO22X1 g8093__8246(.A0 (\memory[3] [7]), .A1 (n_173), .B0
       (data_in[7]), .B1 (n_172), .Y (n_157));
  AO22X1 g8094__7098(.A0 (\memory[4] [0]), .A1 (n_154), .B0
       (data_in[0]), .B1 (n_153), .Y (n_156));
  AO22X1 g8095__6131(.A0 (\memory[4] [1]), .A1 (n_154), .B0
       (data_in[1]), .B1 (n_153), .Y (n_155));
  AO22X1 g8096__1881(.A0 (\memory[4] [2]), .A1 (n_154), .B0
       (data_in[2]), .B1 (n_153), .Y (n_152));
  AO22X1 g8097__5115(.A0 (\memory[4] [3]), .A1 (n_154), .B0
       (data_in[3]), .B1 (n_153), .Y (n_151));
  AO22X1 g8098__7482(.A0 (\memory[4] [4]), .A1 (n_154), .B0
       (data_in[4]), .B1 (n_153), .Y (n_150));
  AO22X1 g8099__4733(.A0 (\memory[4] [5]), .A1 (n_154), .B0
       (data_in[5]), .B1 (n_153), .Y (n_149));
  AO22X1 g8100__6161(.A0 (\memory[4] [6]), .A1 (n_154), .B0
       (data_in[6]), .B1 (n_153), .Y (n_148));
  AO22X1 g8101__9315(.A0 (\memory[4] [7]), .A1 (n_154), .B0
       (data_in[7]), .B1 (n_153), .Y (n_147));
  AO22X1 g8102__9945(.A0 (\memory[5] [0]), .A1 (n_144), .B0
       (data_in[0]), .B1 (n_143), .Y (n_146));
  AO22X1 g8103__2883(.A0 (\memory[5] [1]), .A1 (n_144), .B0
       (data_in[1]), .B1 (n_143), .Y (n_145));
  AO22X1 g8104__2346(.A0 (\memory[5] [2]), .A1 (n_144), .B0
       (data_in[2]), .B1 (n_143), .Y (n_142));
  AO22X1 g8105__1666(.A0 (\memory[5] [3]), .A1 (n_144), .B0
       (data_in[3]), .B1 (n_143), .Y (n_141));
  AO22X1 g8106__7410(.A0 (\memory[5] [4]), .A1 (n_144), .B0
       (data_in[4]), .B1 (n_143), .Y (n_140));
  AO22X1 g8107__6417(.A0 (\memory[5] [5]), .A1 (n_144), .B0
       (data_in[5]), .B1 (n_143), .Y (n_139));
  AO22X1 g8108__5477(.A0 (\memory[5] [6]), .A1 (n_144), .B0
       (data_in[6]), .B1 (n_143), .Y (n_138));
  AO22X1 g8109__2398(.A0 (\memory[5] [7]), .A1 (n_144), .B0
       (data_in[7]), .B1 (n_143), .Y (n_137));
  AO22XL g8110__5107(.A0 (\memory[6] [0]), .A1 (n_134), .B0
       (data_in[0]), .B1 (n_133), .Y (n_136));
  AO22XL g8111__6260(.A0 (\memory[6] [1]), .A1 (n_134), .B0
       (data_in[1]), .B1 (n_133), .Y (n_135));
  AO22XL g8112__4319(.A0 (\memory[6] [2]), .A1 (n_134), .B0
       (data_in[2]), .B1 (n_133), .Y (n_132));
  AO22XL g8113__8428(.A0 (\memory[6] [3]), .A1 (n_134), .B0
       (data_in[3]), .B1 (n_133), .Y (n_131));
  AO22XL g8114__5526(.A0 (\memory[6] [4]), .A1 (n_134), .B0
       (data_in[4]), .B1 (n_133), .Y (n_130));
  AO22XL g8115__6783(.A0 (\memory[6] [5]), .A1 (n_134), .B0
       (data_in[5]), .B1 (n_133), .Y (n_129));
  AO22XL g8116__3680(.A0 (\memory[6] [6]), .A1 (n_134), .B0
       (data_in[6]), .B1 (n_133), .Y (n_128));
  AO22XL g8117__1617(.A0 (\memory[6] [7]), .A1 (n_134), .B0
       (data_in[7]), .B1 (n_133), .Y (n_127));
  AO22X1 g8118__2802(.A0 (\memory[7] [0]), .A1 (n_124), .B0
       (data_in[0]), .B1 (n_123), .Y (n_126));
  AO22X1 g8119__1705(.A0 (\memory[7] [1]), .A1 (n_124), .B0
       (data_in[1]), .B1 (n_123), .Y (n_125));
  AO22X1 g8120__5122(.A0 (\memory[7] [2]), .A1 (n_124), .B0
       (data_in[2]), .B1 (n_123), .Y (n_122));
  AO22X1 g8121__8246(.A0 (\memory[7] [3]), .A1 (n_124), .B0
       (data_in[3]), .B1 (n_123), .Y (n_121));
  AO22X1 g8122__7098(.A0 (\memory[7] [4]), .A1 (n_124), .B0
       (data_in[4]), .B1 (n_123), .Y (n_120));
  AO22X1 g8123__6131(.A0 (\memory[7] [5]), .A1 (n_124), .B0
       (data_in[5]), .B1 (n_123), .Y (n_119));
  AO22X1 g8124__1881(.A0 (\memory[7] [6]), .A1 (n_124), .B0
       (data_in[6]), .B1 (n_123), .Y (n_118));
  AO22X1 g8125__5115(.A0 (\memory[7] [7]), .A1 (n_124), .B0
       (data_in[7]), .B1 (n_123), .Y (n_117));
  AO22XL g8126__7482(.A0 (\memory[8] [0]), .A1 (n_250), .B0
       (data_in[0]), .B1 (n_249), .Y (n_116));
  AO22XL g8127__4733(.A0 (\memory[8] [1]), .A1 (n_250), .B0
       (data_in[1]), .B1 (n_249), .Y (n_115));
  AO22XL g8189__6161(.A0 (\memory[0] [7]), .A1 (n_209), .B0
       (data_in[7]), .B1 (n_208), .Y (n_114));
  AO22XL g8214__9315(.A0 (\memory[9] [4]), .A1 (n_103), .B0
       (\memory[10] [4]), .B1 (n_102), .Y (n_113));
  NAND2XL g8203__9945(.A (\memory[13] [0]), .B (n_110), .Y (n_112));
  NAND2XL g8204__2883(.A (\memory[13] [1]), .B (n_110), .Y (n_111));
  NAND2XL g8205__2346(.A (\memory[13] [2]), .B (n_110), .Y (n_109));
  NAND2XL g8206__1666(.A (\memory[13] [3]), .B (n_110), .Y (n_108));
  NAND2XL g8207__7410(.A (\memory[13] [4]), .B (n_110), .Y (n_107));
  NAND2XL g8208__6417(.A (\memory[13] [5]), .B (n_110), .Y (n_106));
  NAND2XL g8209__5477(.A (\memory[13] [7]), .B (n_110), .Y (n_105));
  AO22XL g8212__2398(.A0 (\memory[9] [7]), .A1 (n_103), .B0
       (\memory[10] [7]), .B1 (n_102), .Y (n_104));
  AOI22XL g8202__5107(.A0 (n_329), .A1 (\memory[4] [5]), .B0 (n_98),
       .B1 (\memory[3] [5]), .Y (n_101));
  AOI22XL g8219__6260(.A0 (n_329), .A1 (\memory[4] [1]), .B0 (n_98),
       .B1 (\memory[3] [1]), .Y (n_100));
  AOI22XL g8220__4319(.A0 (n_329), .A1 (\memory[4] [4]), .B0 (n_98),
       .B1 (\memory[3] [4]), .Y (n_97));
  AOI22X1 g8221__8428(.A0 (\memory[1] [1]), .A1 (n_93), .B0
       (\memory[2] [1]), .B1 (n_95), .Y (n_96));
  AOI22X1 g8222__5526(.A0 (\memory[1] [4]), .A1 (n_93), .B0
       (\memory[2] [4]), .B1 (n_95), .Y (n_94));
  AOI22XL g8224__6783(.A0 (n_91), .A1 (\memory[14] [2]), .B0 (n_270),
       .B1 (\memory[13] [2]), .Y (n_92));
  AOI22XL g8225__3680(.A0 (n_329), .A1 (\memory[4] [0]), .B0 (n_98),
       .B1 (\memory[3] [0]), .Y (n_90));
  AO22XL g8226__1617(.A0 (\memory[9] [5]), .A1 (n_103), .B0
       (\memory[10] [5]), .B1 (n_102), .Y (n_89));
  NAND2XL g8229__2802(.A (\memory[13] [6]), .B (n_110), .Y (n_88));
  AOI22X1 g8247__1705(.A0 (\memory[1] [2]), .A1 (n_93), .B0
       (\memory[2] [2]), .B1 (n_95), .Y (n_87));
  AO22XL g8232__5122(.A0 (\memory[9] [0]), .A1 (n_103), .B0
       (\memory[10] [0]), .B1 (n_102), .Y (n_86));
  AO22XL g8233__8246(.A0 (\memory[9] [2]), .A1 (n_103), .B0
       (\memory[10] [2]), .B1 (n_102), .Y (n_85));
  AO22XL g8237__7098(.A0 (\memory[9] [6]), .A1 (n_103), .B0
       (\memory[10] [6]), .B1 (n_102), .Y (n_84));
  AOI22XL g8239__6131(.A0 (n_329), .A1 (\memory[4] [2]), .B0 (n_98),
       .B1 (\memory[3] [2]), .Y (n_83));
  AOI22XL g8242__1881(.A0 (n_329), .A1 (\memory[4] [6]), .B0 (n_98),
       .B1 (\memory[3] [6]), .Y (n_82));
  AOI22X1 g8244__5115(.A0 (\memory[1] [0]), .A1 (n_93), .B0
       (\memory[2] [0]), .B1 (n_95), .Y (n_81));
  AOI22X1 g8245__7482(.A0 (\memory[1] [6]), .A1 (n_93), .B0
       (\memory[2] [6]), .B1 (n_95), .Y (n_80));
  AOI22XL g8246__4733(.A0 (n_91), .A1 (\memory[14] [7]), .B0 (n_270),
       .B1 (\memory[13] [7]), .Y (n_79));
  AOI22X1 g8231__6161(.A0 (\memory[1] [5]), .A1 (n_93), .B0
       (\memory[2] [5]), .B1 (n_95), .Y (n_78));
  AOI22X1 g8248__9315(.A0 (\memory[0] [3]), .A1 (n_268), .B0
       (\memory[13] [3]), .B1 (n_270), .Y (n_77));
  AOI22XL g8249__9945(.A0 (n_91), .A1 (\memory[14] [1]), .B0 (n_270),
       .B1 (\memory[13] [1]), .Y (n_76));
  AOI22XL g8250__2883(.A0 (n_329), .A1 (\memory[4] [7]), .B0 (n_98),
       .B1 (\memory[3] [7]), .Y (n_75));
  AO22XL g8251__2346(.A0 (\memory[9] [1]), .A1 (n_103), .B0
       (\memory[10] [1]), .B1 (n_102), .Y (n_74));
  AOI22XL g8252__1666(.A0 (n_91), .A1 (\memory[14] [0]), .B0 (n_270),
       .B1 (\memory[13] [0]), .Y (n_73));
  AO22XL g8253__7410(.A0 (\memory[9] [3]), .A1 (n_103), .B0
       (\memory[11] [3]), .B1 (n_299), .Y (n_72));
  AOI22X1 g8254__6417(.A0 (\memory[1] [7]), .A1 (n_93), .B0
       (\memory[2] [7]), .B1 (n_95), .Y (n_71));
  AOI22X1 g8256__5477(.A0 (\memory[1] [3]), .A1 (n_93), .B0
       (\memory[3] [3]), .B1 (n_98), .Y (n_70));
  AOI22X1 g8257__2398(.A0 (\memory[8] [3]), .A1 (n_63), .B0
       (\memory[10] [3]), .B1 (n_102), .Y (n_69));
  AOI22X1 g8210__5107(.A0 (\memory[0] [4]), .A1 (n_268), .B0
       (\memory[14] [4]), .B1 (n_91), .Y (n_68));
  AOI22XL g8211__6260(.A0 (n_65), .A1 (\memory[6] [1]), .B0 (n_61), .B1
       (\memory[5] [1]), .Y (n_67));
  AOI22XL g8213__4319(.A0 (n_329), .A1 (\memory[4] [3]), .B0 (n_65),
       .B1 (\memory[6] [3]), .Y (n_66));
  AOI22X1 g8215__8428(.A0 (\memory[8] [1]), .A1 (n_63), .B0
       (\memory[7] [1]), .B1 (n_59), .Y (n_64));
  AOI22XL g8216__5526(.A0 (n_65), .A1 (\memory[6] [4]), .B0 (n_61), .B1
       (\memory[5] [4]), .Y (n_62));
  AOI22X1 g8217__6783(.A0 (\memory[8] [4]), .A1 (n_63), .B0
       (\memory[7] [4]), .B1 (n_59), .Y (n_60));
  AOI22XL g8218__3680(.A0 (n_65), .A1 (\memory[6] [0]), .B0 (n_61), .B1
       (\memory[5] [0]), .Y (n_58));
  AOI22X1 g8223__1617(.A0 (\memory[0] [5]), .A1 (n_268), .B0
       (\memory[14] [5]), .B1 (n_91), .Y (n_57));
  AOI22XL g8227__2802(.A0 (n_65), .A1 (\memory[6] [5]), .B0 (n_61), .B1
       (\memory[5] [5]), .Y (n_56));
  AOI22X1 g8228__1705(.A0 (\memory[8] [5]), .A1 (n_63), .B0
       (\memory[7] [5]), .B1 (n_59), .Y (n_55));
  AOI22XL g8230__5122(.A0 (n_65), .A1 (\memory[6] [7]), .B0 (n_61), .B1
       (\memory[5] [7]), .Y (n_54));
  AOI22X1 g8234__8246(.A0 (\memory[0] [6]), .A1 (n_268), .B0
       (\memory[14] [6]), .B1 (n_91), .Y (n_53));
  AOI22X1 g8235__7098(.A0 (\memory[8] [0]), .A1 (n_63), .B0
       (\memory[7] [0]), .B1 (n_59), .Y (n_52));
  AOI22XL g8236__6131(.A0 (n_65), .A1 (\memory[6] [2]), .B0 (n_61), .B1
       (\memory[5] [2]), .Y (n_51));
  AOI22X1 g8238__1881(.A0 (\memory[5] [3]), .A1 (n_61), .B0
       (\memory[7] [3]), .B1 (n_59), .Y (n_50));
  AOI22X1 g8240__5115(.A0 (\memory[8] [2]), .A1 (n_63), .B0
       (\memory[7] [2]), .B1 (n_59), .Y (n_49));
  AOI22X1 g8241__7482(.A0 (\memory[8] [6]), .A1 (n_63), .B0
       (\memory[7] [6]), .B1 (n_59), .Y (n_48));
  AOI22XL g8243__4733(.A0 (n_65), .A1 (\memory[6] [6]), .B0 (n_61), .B1
       (\memory[5] [6]), .Y (n_47));
  AOI22X1 g8255__6161(.A0 (\memory[8] [7]), .A1 (n_63), .B0
       (\memory[7] [7]), .B1 (n_59), .Y (n_46));
  NAND2XL g8261__9945(.A (n_44), .B (n_45), .Y (n_110));
  NAND2XL g8258__2883(.A (n_41), .B (n_45), .Y (n_224));
  NAND2XL g8259__2346(.A (n_40), .B (n_45), .Y (n_144));
  NAND2BX1 g8260__1666(.AN (n_43), .B (n_45), .Y (n_154));
  NAND2XL g8268__7410(.A (n_44), .B (n_42), .Y (n_177));
  NAND2BX1 g8262__6417(.AN (n_43), .B (n_39), .Y (n_205));
  NAND2BX1 g8263__5477(.AN (n_43), .B (n_38), .Y (n_209));
  NAND2BX1 g8264__2398(.AN (n_43), .B (n_42), .Y (n_134));
  NOR2XL g8287__5107(.A (n_32), .B (n_37), .Y (n_176));
  NAND2XL g8267__6260(.A (n_41), .B (n_42), .Y (n_197));
  NAND2XL g8269__4319(.A (n_40), .B (n_42), .Y (n_124));
  NAND2XL g8270__8428(.A (n_40), .B (n_39), .Y (n_173));
  NAND2XL g8271__5526(.A (n_40), .B (n_38), .Y (n_213));
  NAND2XL g8272__6783(.A (n_44), .B (n_38), .Y (n_244));
  NAND2XL g8273__3680(.A (n_44), .B (n_39), .Y (n_234));
  NOR2X1 g8286__1617(.A (n_29), .B (n_37), .Y (n_273));
  NAND2XL g8266__2802(.A (n_41), .B (n_38), .Y (n_250));
  NOR2XL g8282__1705(.A (n_31), .B (n_328), .Y (n_299));
  NAND2XL g8281__5122(.A (n_25), .B (n_327), .Y (n_262));
  NOR2XL g8303__8246(.A (n_23), .B (n_328), .Y (n_102));
  NOR2X1 g8299__7098(.A (n_24), .B (n_328), .Y (n_95));
  AND2X1 g8283__6131(.A (n_30), .B (n_327), .Y (n_270));
  NOR2XL g8304__1881(.A (n_27), .B (n_328), .Y (n_98));
  CLKINVX1 g8311(.A (n_327), .Y (n_37));
  NOR2XL g8275__5115(.A (n_21), .B (n_33), .Y (n_38));
  NOR2XL g8274__7482(.A (n_22), .B (n_33), .Y (n_45));
  NOR2XL g8285__4733(.A (n_32), .B (n_28), .Y (n_133));
  NOR2XL g8288__6161(.A (n_31), .B (n_26), .Y (n_243));
  NOR2BX1 g8276__9315(.AN (n_30), .B (n_18), .Y (n_61));
  NOR2XL g8300__9945(.A (n_29), .B (n_28), .Y (n_65));
  NOR2BX1 g8284__2883(.AN (n_30), .B (n_19), .Y (n_300));
  NOR2XL g8289__2346(.A (n_27), .B (n_26), .Y (n_212));
  NOR2BX1 g8306__1666(.AN (n_25), .B (n_28), .Y (n_153));
  NOR2XL g8290__7410(.A (n_24), .B (n_26), .Y (n_208));
  NOR2XL g8291__6417(.A (n_23), .B (n_26), .Y (n_249));
  NOR2XL g8293__5477(.A (n_22), .B (n_20), .Y (n_42));
  NOR2XL g8294__2398(.A (n_21), .B (n_20), .Y (n_39));
  NOR2XL g8297__6260(.A (n_32), .B (n_19), .Y (n_196));
  NOR2BX1 g8302__4319(.AN (n_25), .B (n_19), .Y (n_223));
  NOR2BX1 g8301__8428(.AN (n_25), .B (n_18), .Y (n_143));
  NOR2XL g8305__5526(.A (n_29), .B (n_19), .Y (n_91));
  NOR2XL g8296__6783(.A (n_31), .B (n_17), .Y (n_233));
  NOR2X1 g8308__3680(.A (n_29), .B (n_18), .Y (n_59));
  NOR2XL g8309__1617(.A (n_27), .B (n_17), .Y (n_172));
  NOR2XL g8310__2802(.A (n_23), .B (n_17), .Y (n_281));
  NOR2XL g8298__1705(.A (n_32), .B (n_18), .Y (n_123));
  NOR2XL g8295__5122(.A (n_24), .B (n_17), .Y (n_204));
  NOR2X1 g8278__7098(.A (n_27), .B (n_16), .Y (n_93));
  NOR2X1 g8277__6131(.A (n_31), .B (n_16), .Y (n_103));
  NOR2X1 g8280__5115(.A (n_23), .B (n_16), .Y (n_63));
  NOR2X1 g8279__7482(.A (n_24), .B (n_16), .Y (n_268));
  NOR2XL g8313__4733(.A (rst), .B (n_14), .Y (n_20));
  NAND2BX1 g8320__6161(.AN (n_23), .B (n_21), .Y (n_19));
  NAND2XL g8316__9315(.A (n_22), .B (n_25), .Y (n_26));
  NOR2XL g8312__9945(.A (rst), .B (n_25), .Y (n_33));
  NAND2X1 g8323__2883(.A (n_10), .B (n_21), .Y (n_28));
  NAND2XL g8322__2346(.A (n_22), .B (n_14), .Y (n_17));
  NAND2BX1 g8325__1666(.AN (n_27), .B (n_21), .Y (n_18));
  NAND2XL g8326__7410(.A (n_23), .B (n_13), .Y (n_41));
  NAND2X1 g8317__6417(.A (n_30), .B (n_22), .Y (n_16));
  NAND2XL g8315__5477(.A (n_27), .B (n_13), .Y (n_40));
  NOR2XL g8318__2398(.A (n_10), .B (rst), .Y (n_43));
  NAND2XL g8321__5107(.A (n_31), .B (n_13), .Y (n_44));
  CLKINVX1 g8328(.A (n_32), .Y (n_14));
  NOR2X1 g8330__6260(.A (addr[1]), .B (n_8), .Y (n_25));
  INVXL g8327(.A (n_10), .Y (n_24));
  NAND2X2 g8338__4319(.A (addr[1]), .B (n_8), .Y (n_29));
  CLKAND2X2 g8334__8428(.A (addr[2]), .B (n_13), .Y (n_21));
  NOR2XL g8342__5526(.A (rst), .B (n_8), .Y (n_272));
  NOR2XL g8331__6783(.A (addr[3]), .B (addr[0]), .Y (n_10));
  NAND2XL g8340__3680(.A (addr[0]), .B (addr[3]), .Y (n_31));
  NOR2X1 g8332__1617(.A (addr[2]), .B (rst), .Y (n_22));
  NOR2X1 g8337__2802(.A (addr[1]), .B (we), .Y (n_30));
  NAND2XL g8333__1705(.A (addr[1]), .B (we), .Y (n_32));
  NAND2BXL g8339__5122(.AN (addr[0]), .B (addr[3]), .Y (n_23));
  NAND2BXL g8341__8246(.AN (addr[3]), .B (addr[0]), .Y (n_27));
  INVXL g8344(.A (data_in[1]), .Y (n_7));
  INVXL g8349(.A (data_in[3]), .Y (n_6));
  INVXL g8351(.A (data_in[6]), .Y (n_5));
  INVXL g8347(.A (data_in[0]), .Y (n_4));
  CLKINVX1 g8348(.A (rst), .Y (n_13));
  INVXL g8352(.A (data_in[4]), .Y (n_3));
  INVXL g8346(.A (data_in[7]), .Y (n_2));
  INVXL g8345(.A (data_in[2]), .Y (n_1));
  INVXL g8350(.A (data_in[5]), .Y (n_0));
  CLKINVX2 g8343(.A (we), .Y (n_8));
  NAND2XL g2(.A (n_41), .B (n_39), .Y (n_326));
  NOR2BX1 g8489(.AN (n_21), .B (n_31), .Y (n_327));
  NAND2BX1 g8490(.AN (n_29), .B (n_22), .Y (n_328));
  NOR2BX1 g8491(.AN (n_30), .B (n_28), .Y (n_329));
endmodule

